name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run tests (optional)
        working-directory: ./backend
        run: |
          echo "No tests defined yet"

      - name: Build Docker image
        run: |
          docker build -t project-cicd-backend ./backend
